"""Comment.body_html

Revision ID: 2e5eac167183
Revises: 57c60219becc
Create Date: 2015-04-25 15:44:28.589525

"""

# revision identifiers, used by Alembic.
revision = '2e5eac167183'
down_revision = '57c60219becc'

from alembic import op
import sqlalchemy as sa
from app.models import Comment
from app import db

class CommentNew(db.Model):
    __tablename__ = 'comments-new'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True)
    disabled = db.Column(db.Boolean)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # create a new table "comments-new"

    comments = []

    for comment in db.session.query(Comment):
        new_comment = CommentNew(body=comment.body,
                                 body_html=comment.bobdy_html,
                                 timestamp=comment.timestamp,
                                 disabled=comment.disabled,
                                 author_id=comment.author_id,
                                 post_id=comment.post_id)
        comments.append(new_comment)

    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')

    op.create_table('comments-new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments-new', ['timestamp'], unique=False)

    for comment in comments:
        db.session.add(comment)
    db.session.commit()
    op.rename_table('comments-new', 'comments')

    #op.alter_column('comments', 'bobdy_html', new_column_name='body_html')
    #op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    #op.drop_column('comments', 'bobdy_html')
    ### end Alembic commands ###


def downgrade():
    print "We do not support downgrading to the previous version."
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('comments', 'body_html', new_column_name='bobdy_html')
    #op.add_column('comments', sa.Column('bobdy_html', sa.TEXT(), nullable=True))
    #op.drop_column('comments', 'body_html')
    ### end Alembic commands ###
