"""caching of avatar hashes

Revision ID: 32074f4e4fd8
Revises: 222f09e8cf87
Create Date: 2015-04-01 22:47:28.151653

"""

# revision identifiers, used by Alembic.
revision = '32074f4e4fd8'
down_revision = '222f09e8cf87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
