"""empty message

Revision ID: 7e29ed01651
Revises: 27b3d7f0f240
Create Date: 2015-03-12 23:04:55.379330

"""

# revision identifiers, used by Alembic.
revision = '7e29ed01651'
down_revision = '27b3d7f0f240'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
